version: '3.9'

services:

    php:
        container_name: m2_php_1
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - appdata:/var/www
            - ../htdocs:/var/www/htdocs:cached
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PHP_XDEBUG_ENABLED: 0
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=dopelore.local"
        networks:
            - magento2_net

    nginx:
        container_name: m2_nginx_1
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ../htdocs:/var/www/htdocs:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - magento2_net

    db:
        container_name: m2_db_1
        image: mariadb:10.4
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - magento2_net

    phpmyadmin:
        container_name: m2_phpmyadmin_1
        image: phpmyadmin:latest
        ports:
            - '8080:80'
        networks:
            - magento2_net
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: docker

    redis:
        container_name: m2_redis_1
        image: redis:latest
        networks:
            - magento2_net

    redisinsight:
      container_name: m2_redisinsight_1
      image: redislabs/redisinsight:latest
      ports:
          - 8001:8001

    elasticsearch:
        container_name: m2_elasticsearch_1
        image: elasticsearch:7.9.3
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            "discovery.type": "single-node"
        networks:
            - magento2_net

networks:
    magento2_net:

volumes:
    appdata:


